#
# Makefile for the video capture/playback device drivers.
#
obj-$(CONFIG_WMT_VIDEO_DECODE_VPX) += wmt-vpx.o hantro/vp8_api.o hantro/vp8_asic.o hantro/vp8_bool.o hantro/vp8_buffer.o hantro/vp8_coder.o hantro/vp8_dwl.o

